Error while building message. Error while building Passthrough stream org.apache.axis2.AxisFault: Error while building Passthrough stream
Access Denied. Failed authorization attempt to access service 'UserStoreConfigAdminService' operation 'getSecondaryRealmConfigurations' by 'monica.f.borges@nosi.cv'
Access Denied. Failed authorization attempt to access service 'UserStoreCountService' operation 'getCountEnabledUserStores' by 'monica.f.borges@nosi.cv'
Access Denied. org.apache.axis2.AxisFault: Access Denied.
The endpoint reference (EPR) for the Operation not found is /services/echo and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator. org.apache.axis2.AxisFault: The endpoint reference (EPR) for the Operation not found is /services/echo and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.
The endpoint reference (EPR) for the Operation not found is /services/WorkflowCallbackService and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator. org.apache.axis2.AxisFault: The endpoint reference (EPR) for the Operation not found is /services/WorkflowCallbackService and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.
Uncaught exception java.lang.OutOfMemoryError: Java heap space
Uncaught exception java.lang.NullPointerException
Exception processing background thread java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception java.lang.IllegalArgumentException: An invalid character [59] was present in the Cookie value
Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception java.lang.IllegalArgumentException: An invalid character [44] was present in the Cookie value
Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception org.apache.axis2.AxisFault
Servlet.service() for servlet [bridgeservlet] threw exception java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception org.wso2.carbon.identity.application.authentication.framework.inbound.FrameworkRuntimeException: org.wso2.carbon.identity.application.authentication.framework.inbound.FrameworkRuntimeException: No IdentityProcessor found to process the request
Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception java.lang.ArrayIndexOutOfBoundsException
Error processing async timeouts java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
Error processing request java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: "%0"
Error creating core [registry-indexing]: /home/wso2carbon/wso2am-3.2.0/solr/data/index/write.lock org.apache.solr.common.SolrException: /home/wso2carbon/wso2am-3.2.0/solr/data/index/write.lock
org.apache.solr.common.SolrException: java.io.FileNotFoundException: /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019996 (No such file or directory)
org.apache.solr.common.SolrException: java.io.FileNotFoundException: /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019996 (Permission denied)
auto commit error...:java.nio.file.AccessDeniedException: /home/wso2carbon/wso2am-3.2.0/solr/data/index/_3vp0.fnm
auto commit error...:org.apache.solr.common.SolrException: Error opening new searcher
auto commit error...:java.nio.file.NoSuchFileException: /home/wso2carbon/wso2am-3.2.0/solr/data/index/pending_segments_fbd
Failure to open existing log file (non fatal) /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019916:org.apache.solr.common.SolrException: java.io.FileNotFoundException: /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019916 (Permission denied)
Failure to open existing log file (non fatal) /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019917:org.apache.solr.common.SolrException: java.io.FileNotFoundException: /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019917 (Permission denied)
Failure to open existing log file (non fatal) /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019918:org.apache.solr.common.SolrException: java.io.FileNotFoundException: /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019918 (Permission denied)
Failure to open existing log file (non fatal) /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019919:org.apache.solr.common.SolrException: java.io.FileNotFoundException: /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019919 (Permission denied)
Failure to open existing log file (non fatal) /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019920:org.apache.solr.common.SolrException: java.io.FileNotFoundException: /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019920 (Permission denied)
Failure to open existing log file (non fatal) /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019921:org.apache.solr.common.SolrException: java.io.FileNotFoundException: /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019921 (Permission denied)
Failure to open existing log file (non fatal) /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019922:org.apache.solr.common.SolrException: java.io.FileNotFoundException: /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019922 (Permission denied)
Failure to open existing log file (non fatal) /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019923:org.apache.solr.common.SolrException: java.io.FileNotFoundException: /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019923 (Permission denied)
Failure to open existing log file (non fatal) /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019924:org.apache.solr.common.SolrException: java.io.FileNotFoundException: /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019924 (Permission denied)
Failure to open existing log file (non fatal) /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019925:org.apache.solr.common.SolrException: java.io.FileNotFoundException: /home/wso2carbon/wso2am-3.2.0/solr/data/tlog/tlog.0000000000000019925 (Permission denied)
Replay exception: final commit. java.nio.file.AccessDeniedException: /home/wso2carbon/wso2am-3.2.0/solr/data/index/_3vp0.fnm
#writeAsJson. Payload could not be written as JSON. MessageID: urn:uuid:cebc1828-a03e-4e3a-a265-480ddd042969
#writeAsJson. Payload could not be written as JSON. MessageID: urn:uuid:47415919-25b2-492a-a3cd-fa57c4d952a5
#writeAsJson. Payload could not be written as JSON. MessageID: urn:uuid:ea756974-c5f3-4eef-93b9-0afd70f950ac
{api:adminsuper-AT-nosi.cv-AT-carbon.super--GeografiaINGTAPI:v1.0.0} accept:application/json,Access-Control-Allow-Headers:authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction,apikey,testKey,Access-Control-Allow-Methods:POST,Access-Control-Allow-Origin:*,Access-Control-Expose-Headers:,cache-control:no-cache,charset:utf-8,Content-Type:application/json,host:integrator-stage-pdex.gov.cv:8282,pragma:no-cache,soapaction:urn:select_geo_by_id,x-forwarded-for:10.32.0.1,x-forwarded-host:gateway-pdex.gov.cv,x-forwarded-port:443,x-forwarded-proto:https,x-forwarded-scheme:https,x-original-forwarded-for:10.6.6.34,x-real-ip:10.32.0.1,x-request-id:7f0a89fd0aaeca37f5a52e83534bec1c,x-scheme:https, Unexpected error sending message back org.apache.axis2.AxisFault: Failed to submit the response
{api:adminsuper-AT-nosi.cv-AT-carbon.super--GeografiaINGTAPI:v1.0.0} accept:application/json,Access-Control-Allow-Headers:authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction,apikey,testKey,Access-Control-Allow-Methods:POST,Access-Control-Allow-Origin:*,Access-Control-Expose-Headers:,cache-control:no-cache,charset:utf-8,Content-Type:application/json,host:integrator-stage-pdex.gov.cv:8282,pragma:no-cache,soapaction:urn:select_geo_by_id,x-forwarded-for:10.40.0.0,x-forwarded-host:gateway-pdex.gov.cv,x-forwarded-port:443,x-forwarded-proto:https,x-forwarded-scheme:https,x-original-forwarded-for:10.6.6.34,x-real-ip:10.40.0.0,x-request-id:df23b1595b0292f67bf0cd1713627f55,x-scheme:https, Unexpected error sending message back org.apache.axis2.AxisFault: Failed to submit the response
{api:adminsuper-AT-nosi.cv-AT-carbon.super--GeografiaINGTAPI:v1.0.0} accept:application/json,Access-Control-Allow-Headers:authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction,apikey,testKey,Access-Control-Allow-Methods:POST,Access-Control-Allow-Origin:*,Access-Control-Expose-Headers:,cache-control:no-cache,charset:utf-8,Content-Type:application/json,host:integrator-stage-pdex.gov.cv:8282,pragma:no-cache,soapaction:urn:select_geo_by_id,x-forwarded-for:10.32.0.1,x-forwarded-host:gateway-pdex.gov.cv,x-forwarded-port:443,x-forwarded-proto:https,x-forwarded-scheme:https,x-original-forwarded-for:10.6.6.48,x-real-ip:10.32.0.1,x-request-id:bf355b47c6cbd1a896a386c120985ed1,x-scheme:https, Unexpected error sending message back org.apache.axis2.AxisFault: Failed to submit the response
Deployment of the Synapse Artifact from file : /home/wso2carbon/wso2am-3.2.0/repository/deployment/server/synapse-configs/default/sequences/fault.xml : Failed! org.apache.synapse.deployers.SynapseArtifactDeploymentException: Sequence Deployment from the file : /home/wso2carbon/wso2am-3.2.0/repository/deployment/server/synapse-configs/default/sequences/fault.xml : Failed.
Deployment of the Synapse Artifact from file : /home/wso2carbon/wso2am-3.2.0/repository/deployment/server/synapse-configs/default/sequences/main.xml : Failed! org.apache.synapse.deployers.SynapseArtifactDeploymentException: Sequence Deployment from the file : /home/wso2carbon/wso2am-3.2.0/repository/deployment/server/synapse-configs/default/sequences/main.xml : Failed.
Unable to undeploy the artifact from file : /home/wso2carbon/wso2am-3.2.0/repository/deployment/server/synapse-configs/default/sequences/main.xml org.apache.synapse.deployers.SynapseArtifactDeploymentException: Sequence Undeployement of sequence named : main : Failed
Unable to undeploy the artifact from file : /home/wso2carbon/wso2am-3.2.0/repository/deployment/server/synapse-configs/default/sequences/fault.xml org.apache.synapse.deployers.SynapseArtifactDeploymentException: Sequence Undeployement of sequence named : fault : Failed
{api:_OpenService_} Error while building message. Error while building Passthrough stream org.apache.axis2.AxisFault: Error while building Passthrough stream
Error parsing message envelope org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 148; Attribute name "_duc" associated with an element type "p" must be followed by the ' = ' character.
Error processing GET request for : /service/apexec.pl?etype=odp&template=../../../../../../../../../etc/passwd%%0000.html&passurl=/category/ due to an error in the request sent by the client java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: "%0"
Failed to submit the response org.apache.axis2.AxisFault: Payload could not be written as JSON.
Error while building message for REST_URL request
Error processing GET request for : /services/echo org.apache.axis2.AxisFault: The endpoint reference (EPR) for the Operation not found is /services/echo and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.
Error processing GET request for : /services/WorkflowCallbackService org.apache.axis2.AxisFault: The endpoint reference (EPR) for the Operation not found is /services/WorkflowCallbackService and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.
Error processing GET request for : /t/img/favicon.ico. java.lang.RuntimeException: Error while getting tenant activation status.
HttpException occurred org.apache.http.MethodNotSupportedException: OPENVASVT method not supported
HttpException occurred org.apache.http.ProtocolException: Invalid request line: HELP
HttpException occurred org.apache.http.ProtocolException: Not a valid protocol version:
HttpException occurred org.apache.http.MethodNotSupportedException: VTTEST method not supported
HttpException occurred org.apache.http.ProtocolException: Not a valid protocol version:  Secure-HTTP/1.4
HttpException occurred org.apache.http.ProtocolException: Not a valid protocol version:  Website/Install/InstallWizard.aspx HTTP/1.1
HttpException occurred org.apache.http.ProtocolException: Not a valid protocol version:  Website/DesktopModules/AuthenticationServices/OpenID/license.txt HTTP/1.1
Unexpected I/O error: java.nio.channels.ClosedChannelException java.nio.channels.ClosedChannelException
HttpException occurred org.apache.http.ProtocolException: Invalid request line: id;
HttpException occurred org.apache.http.ProtocolException: Invalid header: uname=admin%27+OR+%271%3D1&pword=%27+OR+%271%3D1
HttpException occurred org.apache.http.ProtocolException: Not a valid protocol version:  union select 1,2,3,4,5,username,password,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74 from tbllogin "having 1=1--" HTTP/1.1
HttpException occurred org.apache.http.ProtocolException: Not a valid protocol version:  and 1=1 HTTP/1.1
HttpException occurred org.apache.http.ProtocolException: Invalid request line: 
HttpException occurred org.apache.http.ProtocolException: Invalid request line: ¥
HttpException occurred org.apache.http.ProtocolException: Invalid request line: Ë
HttpException occurred org.apache.http.ProtocolException: Invalid request line: å
HttpException occurred org.apache.http.ProtocolException: Invalid request line: Â
HttpException occurred org.apache.http.ProtocolException: Invalid request line: 
HttpException occurred org.apache.http.ProtocolException: Not a valid protocol version:  request
HttpException occurred org.apache.http.MethodNotSupportedException: TRACK method not supported
HttpException occurred org.apache.http.ProtocolException: Invalid request line: ¿
HttpException occurred org.apache.http.ProtocolException: Invalid request line: C
HttpException occurred org.apache.http.ProtocolException: Invalid request line: GET /tunnel
HttpException occurred org.apache.http.ProtocolException: Not a valid protocol version:  Website/default.aspx HTTP/1.1
I/O error: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Error building message org.apache.axis2.AxisFault: Processing of multipart/form-data request failed. Stream ended unexpectedly
Error while building Passthrough stream java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 77
Error while building Passthrough stream org.apache.axis2.AxisFault: Processing of multipart/form-data request failed. Stream ended unexpectedly
Error while building Passthrough stream org.apache.axiom.om.OMException: localname can not be null or empty
Error while building Passthrough stream org.apache.axiom.om.OMException: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character 'D' (code 68) in prolog; expected '<'
Error while building Passthrough stream java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 18
Error while building Passthrough stream java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 54
JSPException while including path '/userstore_config/index.jsp'. javax.servlet.jsp.JspException: ServletException while including page.
Error during rendering javax.servlet.jsp.JspException: IO Error executing tag: JSPException while including path '/userstore_config/index.jsp'. ServletException while including page.
IO Error executing tag: JSPException while including path '/userstore_config/index.jsp'. ServletException while including page. java.io.IOException: JSPException while including path '/userstore_config/index.jsp'. ServletException while including page.
Throwable Received but no listener set. org.wso2.andes.AMQDisconnectedException: Server closed connection and reconnection not permitted.
Error occurred while processing task. Task id AMQP_Topic_cacheinvalidation_NODE:wso2am-pattern-1-am-1-deployment-65685cb974-kmk6k/10.35.0.6 java.lang.OutOfMemoryError: Java heap space
Error occurred while processing task. Task id AMQP_Topic_notification_NODE:wso2am-pattern-1-am-1-deployment-65685cb974-kmk6k/10.35.0.6 java.lang.OutOfMemoryError: Java heap space
Error occurred while executing SlotTimeoutTask java.lang.OutOfMemoryError: Java heap space
Exception caught by Mina java.io.IOException: Connection reset by peer
API authentication failure due to Unclassified Authentication Failure org.wso2.carbon.apimgt.gateway.handlers.security.APISecurityException: Unclassified Authentication Failure
Invalid JWT token. XXXXX":"RS256"}
Error occurred while updating OAuth Client : org.wso2.carbon.apimgt.impl.kmclient.KeyManagerClientException: Received status code: 405 Reason:
Unable to find the certificate java.io.FileNotFoundException: /home/wso2carbon/wso2am-3.2.0/repository/resources/security/client-truststore.jks (No such file or directory)
Key Manager Resident Key Manager already initialized in tenant nosica.gov
Key Manager Resident Key Manager already initialized in tenant egov.cv
Key Manager Resident Key Manager already initialized in tenant casacidadao.gov
Key Manager Resident Key Manager already initialized in tenant nosigis.gov
Key Manager Resident Key Manager already initialized in tenant igrp.cv
Key Manager Resident Key Manager already initialized in tenant dgtr.gov
Key Manager Resident Key Manager already initialized in tenant ms.gov
Key Manager Resident Key Manager already initialized in tenant comvida.gov
Key Manager Resident Key Manager already initialized in tenant demo.gov
Key Manager Resident Key Manager already initialized in tenant sim.gov
Key Manager Resident Key Manager already initialized in tenant cmd.gov
Key Manager Resident Key Manager already initialized in tenant educacao.gov.cv
Key Manager Resident Key Manager already initialized in tenant ingt.gov
Key Manager Resident Key Manager already initialized in tenant eleicoes.gov
Key Manager Resident Key Manager already initialized in tenant financas.gov
Key Manager Resident Key Manager already initialized in tenant sniac.gov
Key Manager Resident Key Manager already initialized in tenant rni.gov
Key Manager Resident Key Manager already initialized in tenant nosi.gov
Key Manager Resident Key Manager already initialized in tenant mj.gov
Key Manager Resident Key Manager already initialized in tenant pdex.gov
Key Manager Resident Key Manager already initialized in tenant rnisirc.gov
Error while retrieving API : 03f32990-4952-4ba4-b8a2-686a1adb420d org.wso2.carbon.apimgt.api.APIManagementException: User eleicoes@nosi.cv does not have permission to view API : SendEmail
Error while getting subscriptions of the user eleicoes@nosi.cv@eleicoes.gov org.wso2.carbon.apimgt.api.APIManagementException: User eleicoes@nosi.cv does not have permission to view API : SendEmail
An unknown exception has been captured by the global exception mapper. java.lang.NullPointerException
org.wso2.carbon.apimgt.api.APIManagementException: Error occurred while updating OAuth Client :
Authentication failed: Bearer/Basic authentication header is missing
Error while running deployment scheduler.. java.lang.OutOfMemoryError: Java heap space
An error occurred while activating 'org.wso2.carbon.crypto.provider' component. org.wso2.carbon.crypto.api.CryptoException: Internal keystore file does not exist in the path as configured in 'Security.InternalKeyStore.Location' property.
Unable to send events to the endpoint. org.wso2.carbon.databridge.agent.exception.DataEndpointException: Error while trying to publish events to data receiver :wso2am-pattern-1-am-2-service/10.101.82.4:9611
Unable to send events to the endpoint. org.wso2.carbon.databridge.agent.exception.DataEndpointException: Cannot borrow client for tcp://wso2am-pattern-1-am-2-service:9611##adminsuper@nosi.cv@carbon.super
Unable to send events to the endpoint. org.wso2.carbon.databridge.agent.exception.DataEndpointException: Cannot send Events
Error while trying to connect to the endpoint. Cannot borrow client for ssl://wso2am-pattern-1-am-2-service:9711 org.wso2.carbon.databridge.agent.exception.DataEndpointAuthenticationException: Cannot borrow client for ssl://wso2am-pattern-1-am-2-service:9711
Error while trying to connect to the endpoint. Cannot borrow client for ssl://localhost:9711. org.wso2.carbon.databridge.agent.exception.DataEndpointLoginException: Cannot borrow client for ssl://localhost:9711.
Error while trying to connect to the endpoint. Cannot borrow client for ssl://wso2am-pattern-1-am-2-service:9711. org.wso2.carbon.databridge.agent.exception.DataEndpointLoginException: Cannot borrow client for ssl://wso2am-pattern-1-am-2-service:9711.
Error while trying to connect to the endpoint. Cannot borrow client for ssl://localhost:9711 org.wso2.carbon.databridge.agent.exception.DataEndpointAuthenticationException: Cannot borrow client for ssl://localhost:9711
Error while reading from the socket. javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
Error acquiring a Connection from the JMS CF : jmsEventPublisher2 using properties : {transport.jms.ConcurrentPublishers=allow, java.naming.provider.url=repository/conf/jndi2.properties, java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory, transport.jms.DestinationType=topic, transport.jms.ConnectionFactoryJNDIName=TopicConnectionFactory, transport.jms.Destination=throttleData} javax.jms.JMSException: Error creating connection: Could not open connection
Error acquiring a Connection from the JMS CF : jmsEventPublisher2 using properties : {transport.jms.ConcurrentPublishers=allow, java.naming.provider.url=repository/conf/jndi2.properties, java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory, transport.jms.DestinationType=topic, transport.jms.ConnectionFactoryJNDIName=TopicConnectionFactory, transport.jms.Destination=throttleData} org.wso2.carbon.event.output.adapter.core.exception.OutputEventAdapterRuntimeException: Error acquiring a Connection from the JMS CF : jmsEventPublisher2 using properties : {transport.jms.ConcurrentPublishers=allow, java.naming.provider.url=repository/conf/jndi2.properties, java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory, transport.jms.DestinationType=topic, transport.jms.ConnectionFactoryJNDIName=TopicConnectionFactory, transport.jms.Destination=throttleData}
Object AMQConnection:
null java.lang.NullPointerException
Exception in Authentication Framework org.wso2.carbon.identity.application.authentication.framework.exception.FrameworkException: Error while storing federated authentication session details of the authenticated user to the database
Context does not exist. Probably due to invalidated cache. Requested client: 10.40.0.11, URI :POST:/commonauth, User-Agent: Apache-HttpClient/4.3.6 (java 1.5) , Referer: null
Context does not exist. Probably due to invalidated cache. Requested client: 10.32.0.28, URI :POST:/commonauth, User-Agent: Apache-HttpClient/4.3.6 (java 1.5) , Referer: null
Context does not exist. Probably due to invalidated cache. Requested client: 10.35.0.25, URI :POST:/commonauth, User-Agent: Apache-HttpClient/4.3.6 (java 1.5) , Referer: null
java.lang.NullPointerException
Error while finding application state for application with client_id: wruieytioqrwtqowrtyoqwit
Error occurred while issuing the access token for Client ID : sDE9ErVrScW7z5t2zyTNjgYJpWYa, User ID null, Scope : [] and Grant Type : client_credentials org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: Error occurred while storing new access token : eyJ4NXQiOiJNRGd4WkRNd09XTmxZV0kxTUdVNVlUQTVORE15TlRjMU1XRmtabVV4WVRRell6RTROelZtTnpkaU9EVm1Zemd3TVdNeFlqQTFaV1l6TW1NMk1tVmtNZyIsImtpZCI6Ik1EZ3haRE13T1dObFlXSTFNR1U1WVRBNU5ETXlOVGMxTVdGa1ptVXhZVFF6WXpFNE56Vm1OemRpT0RWbVl6Z3dNV014WWpBMVpXWXpNbU0yTW1Wa01nX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJiY2Fnb3ZjdkBiY2EuY3ZAc25pYWMuZ292IiwiYXV0IjoiQVBQTElDQVRJT04iLCJhdWQiOiJzREU5RXJWclNjVzd6NXQyenlUTmpnWUpwV1lhIiwibmJmIjoxNzMzMTAxMzMwLCJhenAiOiJzREU5RXJWclNjVzd6NXQyenlUTmpnWUpwV1lhIiwic2NvcGUiOiJkZWZhdWx0IiwiaXNzIjoiaHR0cHM6XC9cL2xvY2FsaG9zdDo5NDQzXC9vYXV0aDJcL3Rva2VuIiwiZXhwIjoxNzMzMTA0OTMwLCJpYXQiOjE3MzMxMDEzMzAsImp0aSI6ImFhZDAxODY0LTJjY2QtNDIzYi1iMzU5LTMwN2Q1MTQ1ZDUyYyJ9.kfJ-eKR60Z80mrQVMdooqRZWXxgUCsvgYSBsD6GZ9E_mt8NFtY9OU6Mo7J_f5_DXyuQiA069dEor-38-iCMNdYQHeTw7W5fc2jBBukHI56T9f6qoq_8m1zQD6gJHptTexB0hnIns1tXDNnLoKJ0Gct-S-8L9ECILz3QMDOb9KvM5W9f0Tw_mU5A6aKj9pHF7xM9FKgmPLmd4Tqqn-burQFJ2ZZo5XkqrHt8Eaph4-N2ilfIVpw52T9Izi2l7N__ztvI4mMy1F__EbT2zu4ReyBFQAg7oDtc_iuHfLxsQp9dQXlP9zzUXbnQtYV_40iYAKGC5hDQ_Xel2CFkPEzD4Ow
Error occurred while building the introspection response org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: Error occurred while validating token.
Error in retrieving an Application (Service Provider) with client ID : wruieytioqrwtqowrtyoqwit org.wso2.carbon.identity.oauth.common.exception.InvalidOAuthClientException: Cannot find an application associated with the given consumer key : wruieytioqrwtqowrtyoqwit
Sequence named : fault already exists.
Sequence Deployment from the file : /home/wso2carbon/wso2am-3.2.0/repository/deployment/server/synapse-configs/default/sequences/fault.xml : Failed. org.apache.synapse.deployers.SynapseArtifactDeploymentException: Sequence named : fault already exists.
Sequence named : main already exists.
Sequence Deployment from the file : /home/wso2carbon/wso2am-3.2.0/repository/deployment/server/synapse-configs/default/sequences/main.xml : Failed. org.apache.synapse.deployers.SynapseArtifactDeploymentException: Sequence named : main already exists.
Sequence Undeployement of sequence named : main : Failed org.apache.synapse.deployers.SynapseArtifactDeploymentException: Cannot Undeploy the main sequence
Cannot Undeploy the main sequence
Cannot Undeploy the fault sequence
Sequence Undeployement of sequence named : fault : Failed org.apache.synapse.deployers.SynapseArtifactDeploymentException: Cannot Undeploy the fault sequence
nullType class java.lang.reflect.InvocationTargetException org.wso2.carbon.user.core.UserStoreException: nullType class java.lang.reflect.InvocationTargetException
Cannot start User Manager Core bundle org.wso2.carbon.user.core.UserStoreException: Cannot initialize the realm.
Error obtaining connection. rai-dc-pdx-ldap-02.gov.cv:1636 javax.naming.CommunicationException: rai-dc-pdx-ldap-02.gov.cv:1636 [Root exception is java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)]
Trying again to get connection.
Error obtaining connection for the second timerai-dc-pdx-ldap-02.gov.cv:1636 javax.naming.CommunicationException: rai-dc-pdx-ldap-02.gov.cv:1636 [Root exception is java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)]
Error occurred while obtaining LDAP connection. Connection URL: ldaps://rai-dc-pdx-ldap-01.gov.cv:1636 ldaps://rai-dc-pdx-ldap-02.gov.cv:1636 org.wso2.carbon.user.core.UserStoreException: Error obtaining connection. rai-dc-pdx-ldap-02.gov.cv:1636
Error occurred while obtaining connection for the second time. org.wso2.carbon.user.core.UserStoreException: Error obtaining connection. rai-dc-pdx-ldap-02.gov.cv:1636
Cannot create connection to LDAP server. Connection URL: ldaps://rai-dc-pdx-ldap-01.gov.cv:1636 ldaps://rai-dc-pdx-ldap-02.gov.cv:1636 Error message: Error occurred while obtaining LDAP connection, LDAP connection circuit breaker state set to: open
Error while sending Revocation Event to https://localhost:9443/internal/data/v1/notify javax.net.ssl.SSLException: hostname in certificate didn't match: <localhost> != <*.gov.cv> OR <*.gov.cv> OR <www.gov.cv> OR <gov.cv>
